export type NexusConfigReferenceScope = "workspace" | "home";
export type NexusConfigReferenceSelector = NexusConfigReferenceScope | "all";

export interface NexusConfigReferenceDocLink {
  label: string;
  href: string;
}

export interface NexusConfigReferenceEntry {
  scope: NexusConfigReferenceScope;
  path: string;
  type: string;
  required?: boolean;
  defaultValue?: string;
  values?: string[];
  summary: string;
  docs?: NexusConfigReferenceDocLink[];
  parserFieldNames?: string[];
}

const conceptsDoc = { label: "Concepts", href: "concepts.md" };
const gettingStartedDoc = { label: "Getting started", href: "getting-started.md" };
const agentTargetsDoc = {
  label: "Agent targets and projection cleanup",
  href: "agent-targets.md",
};
const agentWorkflowsDoc = { label: "Agent workflows", href: "agent-workflows.md" };
const gitWorkflowsDoc = { label: "Git workflow integration", href: "git-workflows.md" };
const multiTrackerDoc = { label: "Multi-tracker work tracking", href: "multi-tracker.md" };
const postgresDoc = {
  label: "PostgreSQL claim authority",
  href: "postgresql-claim-authority.md",
};
const providersDoc = {
  label: "Providers, auth, and hosting",
  href: "providers-auth-hosting.md",
};
const publicationDoc = {
  label: "Publication workflows",
  href: "publication-workflows.md",
};

export const nexusConfigReferenceEntries: NexusConfigReferenceEntry[] = [
  {
    scope: "workspace",
    path: "version",
    type: "1",
    required: true,
    summary: "Workspace config schema version.",
    parserFieldNames: ["version"],
  },
  {
    scope: "workspace",
    path: "id",
    type: "string",
    required: true,
    summary: "Stable workspace id used by local state and generated agent context.",
    docs: [conceptsDoc],
    parserFieldNames: ["id"],
  },
  {
    scope: "workspace",
    path: "name",
    type: "string",
    required: true,
    summary: "Human-readable workspace name.",
    docs: [conceptsDoc],
    parserFieldNames: ["name"],
  },
  {
    scope: "workspace",
    path: "home",
    type: "string | null",
    defaultValue: "null",
    summary: "Optional DevNexus home path override for this workspace.",
    docs: [gettingStartedDoc],
    parserFieldNames: ["home"],
  },
  {
    scope: "workspace",
    path: "repo",
    type: "object",
    required: true,
    summary: "Workspace metadata repository settings.",
    docs: [conceptsDoc],
    parserFieldNames: [
      "repo",
      "kind",
      "remoteUrl",
      "defaultBranch",
      "sourceRoot",
    ],
  },
  {
    scope: "workspace",
    path: "worktreesRoot",
    type: "string",
    defaultValue: "worktrees",
    summary: "Default workspace-relative directory for prepared worktrees.",
    docs: [agentWorkflowsDoc],
    parserFieldNames: ["worktreesRoot"],
  },
  {
    scope: "workspace",
    path: "components[]",
    type: "array<object>",
    required: true,
    summary: "Source folders or artifacts coordinated by this workspace.",
    docs: [conceptsDoc, gettingStartedDoc],
    parserFieldNames: [
      "components",
      "componentId",
      "sourceComponentId",
      "sourceRoot",
      "sourceControl",
      "relationships",
      "surfaces",
      "verification",
      "publication",
    ],
  },
  {
    scope: "workspace",
    path: "components[].id",
    type: "string",
    required: true,
    summary: "Stable component id used in work items, leases, and commands.",
    parserFieldNames: ["id"],
  },
  {
    scope: "workspace",
    path: "components[].sourceRoot",
    type: "string",
    required: true,
    summary: "Workspace-relative or absolute component source path.",
    docs: [gettingStartedDoc],
    parserFieldNames: ["sourceRoot"],
  },
  {
    scope: "workspace",
    path: "components[].defaultWorkTrackerId",
    type: "string",
    summary: "Default work tracker binding for this component.",
    docs: [multiTrackerDoc],
    parserFieldNames: ["defaultWorkTrackerId"],
  },
  {
    scope: "workspace",
    path: "workTracking",
    type: "object",
    summary: "Legacy/default work tracker selection.",
    docs: [multiTrackerDoc],
    parserFieldNames: ["workTracking", "provider", "storePath"],
  },
  {
    scope: "workspace",
    path: "workTrackers[]",
    type: "array<object>",
    summary: "Named local or provider-backed tracker bindings.",
    docs: [multiTrackerDoc],
    parserFieldNames: [
      "workTrackers",
      "trackerId",
      "provider",
      "providerQuery",
      "providerFilters",
      "statusOptions",
      "statusFieldId",
      "issueType",
      "projectKey",
      "repositoryOwner",
      "repositoryName",
      "repositoryId",
      "boardId",
    ],
  },
  {
    scope: "workspace",
    path: "trackerDiscovery",
    type: "object",
    summary: "Controls work-item discovery, visibility, and query limits.",
    docs: [multiTrackerDoc],
    parserFieldNames: [
      "trackerDiscovery",
      "queryLimit",
      "directExternalSelection",
      "scannedRoles",
      "visibility",
    ],
  },
  {
    scope: "workspace",
    path: "workTrackerCommunication",
    type: "object",
    summary: "Commenting and status-update policy for tracker communication.",
    docs: [multiTrackerDoc, agentWorkflowsDoc],
    parserFieldNames: [
      "workTrackerCommunication",
      "communication",
      "commentPolicy",
    ],
  },
  {
    scope: "workspace",
    path: "agent",
    type: "object",
    summary: "Default agent command, model, reasoning, and tool approval settings.",
    docs: [agentWorkflowsDoc],
    parserFieldNames: [
      "agent",
      "command",
      "model",
      "reasoning",
      "defaultToolsApprovalMode",
    ],
  },
  {
    scope: "workspace",
    path: "agentTargets[]",
    type: "array<object>",
    summary: "Agent client targets that receive generated support such as Codex or Claude config.",
    docs: [agentTargetsDoc],
    parserFieldNames: [
      "agentTargets",
      "targetAgents",
      "target",
      "provider",
      "configPath",
      "includedServers",
      "includedTools",
      "excludedTools",
    ],
  },
  {
    scope: "workspace",
    path: "mcp",
    type: "object",
    summary: "Core MCP exposure and gateway materialization settings.",
    docs: [agentTargetsDoc, agentWorkflowsDoc],
    parserFieldNames: [
      "mcp",
      "gateway",
      "mcpExposure",
      "mcpExposure",
      "mcp",
      "transport",
      "endpoint",
      "tools",
      "serverName",
    ],
  },
  {
    scope: "workspace",
    path: "skills",
    type: "object",
    summary: "Workspace skill projection and agent skill-pack settings.",
    docs: [agentTargetsDoc],
    parserFieldNames: [
      "skills",
      "skillId",
      "path",
      "activationNotes",
      "defaultCorePack",
    ],
  },
  {
    scope: "workspace",
    path: "plugins[]",
    type: "array<object>",
    summary: "Installed plugin projections, MCP servers, skills, and capabilities.",
    docs: [agentTargetsDoc],
    parserFieldNames: [
      "plugins",
      "packageName",
      "packageKind",
      "configFormat",
      "configSchema",
      "capabilities",
      "capabilityTags",
      "mcp",
      "skills",
      "tools",
      "materialization",
    ],
  },
  {
    scope: "workspace",
    path: "hosting",
    type: "object",
    summary: "Provider hosting, repository provisioning, access repair, and remotes.",
    docs: [providersDoc],
    parserFieldNames: [
      "hosting",
      "provider",
      "namespace",
      "repository",
      "repositories",
      "remotes",
      "access",
      "provisioning",
      "allowCreate",
      "allowAccessRepair",
      "allowDefaultBranchRepair",
      "allowInvitationAcceptance",
      "allowLocalRemoteRepair",
      "allowVisibilityRepair",
      "providerMutationAuthProfile",
    ],
  },
  {
    scope: "workspace",
    path: "automation",
    type: "object",
    summary: "Automation selector, executor, verification, publication, and safety policy.",
    docs: [agentWorkflowsDoc, publicationDoc],
    parserFieldNames: [
      "automation",
      "selector",
      "executor",
      "verification",
      "publication",
      "schedule",
      "safety",
      "agent",
    ],
  },
  {
    scope: "workspace",
    path: "automation.selector",
    type: "object",
    summary: "Eligible work-item filters such as statuses, labels, assignees, search, and limit.",
    docs: [agentWorkflowsDoc],
    parserFieldNames: [
      "selector",
      "statuses",
      "labels",
      "excludeLabels",
      "assignees",
      "search",
      "limit",
      "eligibleWorkMode",
    ],
  },
  {
    scope: "workspace",
    path: "automation.verification",
    type: "object",
    summary: "Focused and full verification commands used by automation and handoffs.",
    docs: [agentWorkflowsDoc],
    parserFieldNames: [
      "verification",
      "focusedCommands",
      "fullCommands",
      "runFullVerification",
      "timeoutMs",
    ],
  },
  {
    scope: "workspace",
    path: "automation.publication",
    type: "object",
    summary: "Branch, review, package, release, and credential policy for publishing work.",
    docs: [publicationDoc],
    parserFieldNames: [
      "publication",
      "strategy",
      "remote",
      "targetBranch",
      "push",
      "remoteUrl",
      "pushUrl",
      "sshHostAlias",
      "packagePublish",
      "releasePublish",
      "actor",
      "manualRemote",
      "manualActor",
      "commandEnvironment",
      "greenMain",
      "releaseTrain",
    ],
  },
  {
    scope: "workspace",
    path: "automation.publication.strategy",
    type: "string",
    values: ["local_only", "direct_integration", "review_handoff", "blocked"],
    summary: "Publication strategy selected by automation and PR handoff commands.",
    docs: [publicationDoc],
    parserFieldNames: ["strategy"],
  },
  {
    scope: "workspace",
    path: "automation.publication.gitIdentity",
    type: "object | null",
    summary: "Primary Git author/committer identity plus any co-author trailers.",
    docs: [publicationDoc],
    parserFieldNames: ["gitIdentity"],
  },
  {
    scope: "workspace",
    path: "automation.publication.gitIdentity.name",
    type: "string",
    summary: "Configured primary Git author and committer name.",
    docs: [publicationDoc],
    parserFieldNames: ["name"],
  },
  {
    scope: "workspace",
    path: "automation.publication.gitIdentity.email",
    type: "string",
    summary: "Configured primary Git author and committer email.",
    docs: [publicationDoc],
    parserFieldNames: ["email"],
  },
  {
    scope: "workspace",
    path: "automation.publication.gitIdentity.coAuthors[]",
    type: "array<object>",
    summary: "Additional commit trailer identities rendered as Co-authored-by lines.",
    docs: [publicationDoc],
    parserFieldNames: ["coAuthors"],
  },
  {
    scope: "workspace",
    path: "automation.publication.gitIdentity.coAuthors[].name",
    type: "string",
    required: true,
    summary: "Co-author display name for the exact Co-authored-by trailer.",
    docs: [publicationDoc],
    parserFieldNames: ["name"],
  },
  {
    scope: "workspace",
    path: "automation.publication.gitIdentity.coAuthors[].email",
    type: "string",
    required: true,
    summary: "Co-author email for the exact Co-authored-by trailer.",
    docs: [publicationDoc],
    parserFieldNames: ["email"],
  },
  {
    scope: "workspace",
    path: "automation.gitWorkflows[]",
    type: "array<object>",
    summary: "Configurable stateful Git workflow decision graphs.",
    docs: [gitWorkflowsDoc],
    parserFieldNames: [
      "gitWorkflows",
      "branchStrategy",
      "branchNaming",
      "allowedBranchStrategies",
      "defaultBranchStrategy",
      "defaultIntentPrefix",
      "allowedIntentPrefixes",
      "decisionGraph",
      "nodes",
      "transitions",
      "startNodeId",
      "template",
      "from",
      "to",
      "summary",
      "requiredEvidence",
      "dryRun",
      "providerWrites",
      "resumeInputs",
      "nextOwner",
      "wrongBase",
      "behind",
      "diverged",
      "finalPullRequest",
      "finalPullRequestCreation",
      "mergeAuthority",
    ],
  },
  {
    scope: "workspace",
    path: "automation.featureBranchDelivery",
    type: "object",
    summary: "Feature branch, integration branch, review branch, and finalization policy.",
    docs: [publicationDoc],
    parserFieldNames: [
      "featureBranchDelivery",
      "activeFeatureId",
      "featureBranchPattern",
      "reviewBranchPattern",
      "integrationBranch",
      "integrationPrefix",
      "candidatePrefix",
      "featureBranchDelivery",
    ],
  },
  {
    scope: "workspace",
    path: "automation.greenMain",
    type: "object",
    summary: "Green-main merge planning, rerun, check, and freshness policy.",
    docs: [publicationDoc],
    parserFieldNames: [
      "greenMain",
      "requiredChecks",
      "requirePassing",
      "staleChecks",
      "staleAfterMs",
      "ciTiers",
      "gates",
    ],
  },
  {
    scope: "workspace",
    path: "automation.releaseTrain",
    type: "object",
    summary: "Release train batching, candidate branch, promotion, and final PR policy.",
    docs: [publicationDoc],
    parserFieldNames: [
      "releaseTrain",
      "activeVersionId",
      "integrationBranch",
      "candidatePrefix",
      "finalPullRequest",
      "promotion",
    ],
  },
  {
    scope: "workspace",
    path: "automation.workItemClaims",
    type: "object",
    summary: "Local or PostgreSQL-backed work-item claim authority and lease policy.",
    docs: [agentWorkflowsDoc, postgresDoc],
    parserFieldNames: [
      "workItemClaims",
      "authority",
      "leaseDurationMs",
      "heartbeatIntervalMs",
      "staleClaimPolicy",
      "postgres",
      "connectionProfileId",
    ],
  },
  {
    scope: "workspace",
    path: "hosts[]",
    type: "array<object>",
    summary: "Known execution hosts and host-local safety hints.",
    docs: [agentWorkflowsDoc],
    parserFieldNames: [
      "hosts",
      "hostId",
      "sshHost",
      "tailscaleAddress",
      "capabilityTags",
      "hostLocalSafetyHints",
    ],
  },
  {
    scope: "workspace",
    path: "runnerProfiles[]",
    type: "array<object>",
    summary: "Remote execution runner profiles, command profiles, and host requirements.",
    docs: [agentWorkflowsDoc],
    parserFieldNames: [
      "runnerProfiles",
      "profiles",
      "commandProfileRefs",
      "requiredCapabilities",
      "command",
      "args",
      "timeoutMs",
      "mutationClass",
    ],
  },
  {
    scope: "workspace",
    path: "authority",
    type: "object",
    summary: "Actors, roles, bindings, permissions, policy gates, and approval records.",
    docs: [agentWorkflowsDoc, publicationDoc],
    parserFieldNames: [
      "authority",
      "actors",
      "actorId",
      "roles",
      "role",
      "roleBindings",
      "policyGateIds",
      "allowedOperationClasses",
      "approval",
      "approvalRef",
      "requiredPermission",
    ],
  },
  {
    scope: "workspace",
    path: "versionPlanning",
    type: "object",
    summary: "Version scopes, release readiness, and component inclusion policy.",
    docs: [publicationDoc],
    parserFieldNames: [
      "versionPlanning",
      "activeVersionId",
      "versionPolicy",
      "componentId",
      "targetComponents",
      "milestones",
      "release",
    ],
  },
  {
    scope: "home",
    path: "version",
    type: "1",
    required: true,
    summary: "Home config schema version.",
    parserFieldNames: ["version"],
  },
  {
    scope: "home",
    path: "paths.projectsRoot",
    type: "string",
    required: true,
    summary: "Default root for registered project source folders.",
    docs: [gettingStartedDoc],
    parserFieldNames: ["paths", "projectsRoot"],
  },
  {
    scope: "home",
    path: "paths.workspacesRoot",
    type: "string",
    required: true,
    summary: "Default root for DevNexus workspace directories.",
    docs: [gettingStartedDoc],
    parserFieldNames: ["paths", "workspacesRoot"],
  },
  {
    scope: "home",
    path: "projects[]",
    type: "array<object>",
    required: true,
    summary: "Registered DevNexus projects and workspace roots.",
    docs: [gettingStartedDoc],
    parserFieldNames: [
      "projects",
      "projectRoot",
      "workspaceRoots",
      "componentRoots",
      "componentsRoot",
      "worktreesRoot",
    ],
  },
  {
    scope: "home",
    path: "agent",
    type: "object",
    summary: "Host-level default agent command paths and environment keys.",
    docs: [agentWorkflowsDoc],
    parserFieldNames: [
      "agent",
      "command",
      "commandArgs",
      "commandPaths",
      "environmentKeys",
      "shell",
    ],
  },
  {
    scope: "home",
    path: "authProfiles[]",
    type: "array<object>",
    summary: "Host-local provider credential profiles used by workspaces.",
    docs: [providersDoc],
    parserFieldNames: [
      "authProfiles",
      "authProfile",
      "provider",
      "credentialKind",
      "account",
      "githubApp",
      "githubCliConfigDir",
      "gitUserName",
      "gitUserEmail",
      "tokenRefreshBufferSeconds",
      "installationAccount",
      "repositoryScopes",
    ],
  },
  {
    scope: "home",
    path: "authProfiles[].githubApp",
    type: "object",
    summary: "GitHub App installation or user-to-server authentication settings.",
    docs: [providersDoc],
    parserFieldNames: [
      "githubApp",
      "appId",
      "clientId",
      "privateKeyPath",
      "installationAccount",
    ],
  },
  {
    scope: "home",
    path: "claimAuthorityProfiles[]",
    type: "array<object>",
    summary: "Host-local shared claim backends such as PostgreSQL connection profiles.",
    docs: [postgresDoc],
    parserFieldNames: [
      "claimAuthorityProfiles",
      "postgres",
      "connectionString",
      "connectionStringEnv",
      "schema",
    ],
  },
  {
    scope: "home",
    path: "remoteExecution.commandProfiles[]",
    type: "array<object>",
    summary: "Host-local commands that remote execution runner profiles may invoke by id.",
    docs: [agentWorkflowsDoc],
    parserFieldNames: [
      "remoteExecution",
      "commandProfiles",
      "command",
    ],
  },
  {
    scope: "home",
    path: "hostOverlays[]",
    type: "array<object>",
    summary: "Per-host overlays for SSH, Tailscale, runner, and repository paths.",
    docs: [agentWorkflowsDoc, providersDoc],
    parserFieldNames: [
      "hostOverlays",
      "host",
      "hostId",
      "sshHost",
      "sshUser",
      "tailscaleAddress",
      "repositories",
    ],
  },
];

export const nexusConfigReferenceParserFieldNames = [
  "access",
  "account",
  "actions",
  "activationNotes",
  "active",
  "activeFeatureId",
  "activeProfileId",
  "activeVersionId",
  "actor",
  "actorId",
  "actors",
  "agent",
  "agentTargets",
  "allowAccessRepair",
  "allowCreate",
  "allowDefaultBranchRepair",
  "allowDependencyInstall",
  "allowHostMutation",
  "allowInvitationAcceptance",
  "allowLiveServices",
  "allowLocalRemoteRepair",
  "allowNonLoopbackEndpoint",
  "allowVisibilityRepair",
  "allowedBranchStrategies",
  "allowedIntentPrefixes",
  "allowedOperationClasses",
  "apiBaseUrl",
  "appId",
  "appServer",
  "approval",
  "approvalRef",
  "args",
  "artifactRetention",
  "assignees",
  "authProfile",
  "authProfiles",
  "authority",
  "automation",
  "backend",
  "backoff",
  "baseDelayMs",
  "behind",
  "board",
  "boardId",
  "body",
  "branch",
  "branchNaming",
  "branchPublication",
  "branchStrategy",
  "branches",
  "candidatePrefix",
  "capabilities",
  "capabilityTags",
  "checkCommand",
  "ciTiers",
  "claimAuthorityProfiles",
  "cleanup",
  "clientId",
  "command",
  "commandArgs",
  "commandEnvironment",
  "commandPaths",
  "commandProfileRefs",
  "commandProfiles",
  "coAuthors",
  "commentPolicy",
  "communication",
  "componentId",
  "componentRoots",
  "components",
  "componentsRoot",
  "configFormat",
  "configPath",
  "configSchema",
  "conflictWinner",
  "connectionProfileId",
  "connectionString",
  "connectionStringEnv",
  "coordinationHandoffs",
  "coordinatorProfileId",
  "credentialIdentity",
  "credentialKind",
  "cycleLedgerPath",
  "decisionGraph",
  "defaultBranch",
  "defaultBranchStrategy",
  "defaultCorePack",
  "defaultIntentPrefix",
  "defaultToolsApprovalMode",
  "defaultWorkTrackerId",
  "dependencyLinks",
  "description",
  "directExternalSelection",
  "directTargetPush",
  "directory",
  "displayName",
  "diverged",
  "driver",
  "dryRun",
  "eligibleWorkMode",
  "email",
  "enabled",
  "endpoint",
  "environment",
  "environmentKeys",
  "ephemeralThreadDefault",
  "excludeLabels",
  "excludedTools",
  "executor",
  "executorMode",
  "exposure",
  "extensions",
  "failureLimit",
  "fallbackRemote",
  "featureBranchDelivery",
  "featureBranchPattern",
  "finalLimit",
  "finalPullRequest",
  "finalPullRequestCreation",
  "fingerprints",
  "flow",
  "focusedCommands",
  "from",
  "fullCommands",
  "gates",
  "gateway",
  "gitIdentity",
  "gitUserEmail",
  "gitUserName",
  "gitWorkflows",
  "githubApp",
  "githubCliConfigDir",
  "greenMain",
  "handle",
  "handles",
  "heartbeatIntervalMs",
  "home",
  "host",
  "hostId",
  "hostLocalSafetyHints",
  "hostOverlays",
  "hosting",
  "hosts",
  "id",
  "identityRef",
  "importRequiredFirst",
  "includedServers",
  "includedTools",
  "installCommand",
  "installationAccount",
  "integrationBranch",
  "integrationPreference",
  "integrationPrefix",
  "intelligence",
  "intendedUse",
  "intervalMs",
  "invitationPolicy",
  "issueType",
  "itemId",
  "itemKey",
  "itemNumber",
  "items",
  "kind",
  "labels",
  "leaseDurationMs",
  "ledger",
  "license",
  "limit",
  "limits",
  "localPolicy",
  "lock",
  "manualActor",
  "manualInstructions",
  "manualRemote",
  "materialization",
  "maxConcurrentSubagents",
  "maxCycles",
  "maxDelayMs",
  "maxWorkItems",
  "mcp",
  "mcpExposure",
  "mergeAuthority",
  "milestones",
  "missingCredentialBehavior",
  "mode",
  "model",
  "mutationClass",
  "name",
  "nameTemplate",
  "namespace",
  "nextOwner",
  "nodeId",
  "nodes",
  "notes",
  "number",
  "objective",
  "outputByteLimit",
  "outputLineLimit",
  "owner",
  "ownerKind",
  "packageKind",
  "packageName",
  "packagePublish",
  "path",
  "paths",
  "platformTags",
  "plugins",
  "policyGateIds",
  "port",
  "postgres",
  "privateKeyPath",
  "profile",
  "profiles",
  "projectId",
  "projectKey",
  "projectRoot",
  "projects",
  "projectsRoot",
  "promotion",
  "protocol",
  "provenance",
  "provider",
  "providerFilters",
  "providerIdentity",
  "providerMutationAuthProfile",
  "providerQuery",
  "providerWrites",
  "provisioning",
  "publicRewrite",
  "publication",
  "purposes",
  "push",
  "pushUrl",
  "queryLimit",
  "reason",
  "reasoning",
  "relationships",
  "relaunch",
  "release",
  "releasePublish",
  "releaseTrain",
  "remote",
  "remoteExecution",
  "remoteUrl",
  "remotes",
  "repo",
  "repositories",
  "repository",
  "repositoryId",
  "repositoryName",
  "repositoryOwner",
  "repositoryScopes",
  "repositoryUrl",
  "requirePassing",
  "required",
  "requiredCapabilities",
  "requiredChecks",
  "requiredEvidence",
  "requiredPermission",
  "requiredProviderPermissions",
  "resumeInputs",
  "retention",
  "review",
  "reviewBranchPattern",
  "role",
  "roleBindings",
  "roles",
  "runFullVerification",
  "runnerProfiles",
  "safety",
  "scannedRoles",
  "schedule",
  "schema",
  "scope",
  "search",
  "selector",
  "serverName",
  "setup",
  "setupInstructions",
  "setupNotes",
  "shell",
  "skillId",
  "skills",
  "slug",
  "source",
  "sourceComponentId",
  "sourceControl",
  "sourceRoot",
  "sshHost",
  "sshHostAlias",
  "sshUser",
  "staleAfterMs",
  "staleChecks",
  "staleClaimPolicy",
  "start",
  "startNodeId",
  "statePath",
  "statusFieldId",
  "statusOptions",
  "statuses",
  "stopWhenNoEligibleWork",
  "storePath",
  "strategy",
  "summary",
  "surfaces",
  "tailscaleAddress",
  "target",
  "targetAgents",
  "targetBranch",
  "targetComponents",
  "template",
  "timeoutMs",
  "title",
  "to",
  "tokenRefreshBufferSeconds",
  "tools",
  "trackerDiscovery",
  "trackerId",
  "trackerLimits",
  "transitions",
  "transport",
  "trigger",
  "trustSemantics",
  "ttlDays",
  "unknownActorFallbackRole",
  "unscopedName",
  "update",
  "url",
  "valueHint",
  "variable",
  "variant",
  "verification",
  "version",
  "versionPlanning",
  "versionPolicy",
  "visibility",
  "whileEligible",
  "workItemClaims",
  "workTrackerCommunication",
  "workTrackers",
  "workTracking",
  "workspaceRoots",
  "workspacesRoot",
  "worktreesRoot",
  "wrongBase",
] as const;

export function getNexusConfigReferenceEntries(
  scope: NexusConfigReferenceSelector = "all",
): NexusConfigReferenceEntry[] {
  if (scope === "all") {
    return [...nexusConfigReferenceEntries];
  }

  return nexusConfigReferenceEntries.filter((entry) => entry.scope === scope);
}

export function renderNexusConfigReferenceMarkdown(
  scope: NexusConfigReferenceSelector = "all",
): string {
  const lines = [
    "# DevNexus Configuration Reference",
    "",
    "This reference is maintained in `src/config-reference/nexusConfigReference.ts`.",
    "Focused tests compare its parser field index with the workspace, home, and automation config parsers so accepted field names cannot be added silently.",
    "",
    "CLI:",
    "",
    "```bash",
    "dev-nexus config reference --scope all",
    "dev-nexus config reference --scope workspace --json",
    "```",
    "",
  ];

  if (scope === "all" || scope === "workspace") {
    lines.push(
      "## Workspace Config (`dev-nexus.project.json`)",
      "",
      ...renderEntryTable(getNexusConfigReferenceEntries("workspace")),
      "",
    );
  }

  if (scope === "all" || scope === "home") {
    lines.push(
      "## Home Config (`dev-nexus.home.json`)",
      "",
      ...renderEntryTable(getNexusConfigReferenceEntries("home")),
      "",
    );
  }

  lines.push(
    "## Parser Field Index",
    "",
    "Every field name below is accepted by the workspace, home, or automation config parser and is intentionally discoverable here.",
    "The index is field-name based because the parsers also contain nested and provider-specific shapes that do not map cleanly to one JSON schema yet.",
    "",
    ...renderParserFieldIndex(),
    "",
  );

  return `${lines.join("\n").trimEnd()}\n`;
}

function renderEntryTable(entries: NexusConfigReferenceEntry[]): string[] {
  return [
    "| Path | Type | Values | Required | Default | Summary | Docs |",
    "| --- | --- | --- | --- | --- | --- | --- |",
    ...entries.map((entry) =>
      [
        code(entry.path),
        escapeTableCell(escapeMdxText(entry.type)),
        entry.values?.map(code).join(", ") ?? "",
        entry.required ? "yes" : "no",
        entry.defaultValue ? code(entry.defaultValue) : "",
        escapeTableCell(entry.summary),
        renderDocLinks(entry.docs),
      ].join(" | ").replace(/^/, "| ").replace(/$/, " |")
    ),
  ];
}

function renderParserFieldIndex(): string[] {
  const lines: string[] = [];
  for (let index = 0; index < nexusConfigReferenceParserFieldNames.length; index += 8) {
    lines.push(
      nexusConfigReferenceParserFieldNames
        .slice(index, index + 8)
        .map((fieldName) => code(fieldName))
        .join(", "),
    );
  }
  return lines;
}

function renderDocLinks(docs: NexusConfigReferenceDocLink[] | undefined): string {
  if (!docs || docs.length === 0) {
    return "";
  }

  return docs
    .map((doc) => `[${escapeTableCell(doc.label)}](${doc.href})`)
    .join(", ");
}

function code(value: string): string {
  return `\`${value}\``;
}

function escapeTableCell(value: string): string {
  return value.replace(/\|/gu, "\\|");
}

function escapeMdxText(value: string): string {
  return value.replace(/</gu, "&lt;").replace(/>/gu, "&gt;");
}
