import {
  maxNexusAutomationTargetCycleNoteLength,
} from "../automation/nexusAutomationTargetCycle.js";
import {
  maxNexusRemoteExecutionOutputTailLength,
} from "../remote-execution/nexusRemoteExecution.js";
import { nexusPublicationMcpTools } from "./nexusMcpPublicationTools.js";
import { providerCompatibleMcpTools } from "./nexusMcpSchemaCompatibility.js";

export interface McpTool {
  name: string;
  description: string;
  inputSchema: Record<string, unknown>;
}

export const devNexusMcpTools: McpTool[] = [
  {
    name: "project_status",
    description: "Show one DevNexus workspace by registered id or filesystem path.",
    inputSchema: {
      type: "object",
      properties: {
        homePath: { type: "string" },
        detail: { type: "string", enum: ["summary", "full"], default: "summary" },
        project: { type: "string" },
      },
      required: ["project"],
      additionalProperties: false,
    },
  },
  {
    name: "project_hosting_status",
    description: "Report read-only DevNexus workspace hosting status without mutating local remotes or provider state.",
    inputSchema: {
      type: "object",
      properties: {
        homePath: { type: "string" },
        project: { type: "string" },
        projectRoot: { type: "string" },
      },
      additionalProperties: false,
    },
  },
  {
    name: "project_hosting_plan",
    description: "Build a deterministic dry-run DevNexus workspace hosting plan without applying repairs.",
    inputSchema: {
      type: "object",
      properties: {
        homePath: { type: "string" },
        project: { type: "string" },
        projectRoot: { type: "string" },
      },
      additionalProperties: false,
    },
  },
  {
    name: "project_hosting_apply",
    description: "Apply policy-gated DevNexus workspace hosting repairs.",
    inputSchema: {
      type: "object",
      properties: {
        homePath: { type: "string" },
        project: { type: "string" },
        projectRoot: { type: "string" },
      },
      additionalProperties: false,
    },
  },
  {
    name: "automation_status",
    description: "Read DevNexus automation readiness, target context, and eligible work without mutating state.",
    inputSchema: {
      type: "object",
      properties: {
        homePath: { type: "string" },
        detail: { type: "string", enum: ["summary", "full"], default: "summary" },
        project: { type: "string" },
        projectRoot: { type: "string" },
      },
      additionalProperties: false,
    },
  },
  {
    name: "eligible_work",
    description: "List concise DevNexus eligible work grouped by component using the configured automation selector.",
    inputSchema: {
      type: "object",
      properties: {
        homePath: { type: "string" },
        mode: { enum: ["default", "discovery"] },
        project: { type: "string" },
        projectRoot: { type: "string" },
      },
      additionalProperties: false,
    },
  },
  {
    name: "agent_profiles",
    description: "Inspect concise DevNexus coordinator and subagent profile policy without dumping full workspace config.",
    inputSchema: {
      type: "object",
      properties: {
        homePath: { type: "string" },
        project: { type: "string" },
        projectRoot: { type: "string" },
      },
      additionalProperties: false,
    },
  },
  {
    name: "codex_app_server_probe",
    description: "Safely initialize the configured Codex app-server and report advertised methods and capability blockers without starting turns.",
    inputSchema: {
      type: "object",
      properties: {
        homePath: { type: "string" },
        project: { type: "string" },
        projectRoot: { type: "string" },
        profileId: { type: "string" },
      },
      additionalProperties: false,
    },
  },
  {
    name: "automation_heartbeat_prepare",
    description: "Prepare a Codex heartbeat automation recipe and prompt for a DevNexus workspace without mutating Codex or provider state.",
    inputSchema: {
      type: "object",
      properties: {
        homePath: { type: "string" },
        project: { type: "string" },
        projectRoot: { type: "string" },
        name: { type: ["string", "null"] },
        intervalMinutes: { type: ["number", "null"] },
        status: {
          type: ["string", "null"],
          enum: ["ACTIVE", "PAUSED", null],
        },
      },
      additionalProperties: false,
    },
  },
  {
    name: "setup_flow_list",
    description: "List guided DevNexus setup flows for project onboarding and new-machine setup.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: false,
    },
  },
  {
    name: "setup_plan",
    description: "Build a guided setup plan for a DevNexus workspace without reading secrets or mutating host state.",
    inputSchema: {
      type: "object",
      properties: {
        projectRoot: { type: "string" },
        flowId: { type: "string" },
        platform: {
          type: "string",
          enum: ["auto", "macos", "windows", "linux"],
        },
      },
      required: ["projectRoot", "flowId"],
      additionalProperties: false,
    },
  },
  {
    name: "setup_check",
    description: "Check safe local setup facts for a DevNexus workspace without contacting external providers.",
    inputSchema: {
      type: "object",
      properties: {
        projectRoot: { type: "string" },
        flowId: { type: "string" },
        platform: {
          type: "string",
          enum: ["auto", "macos", "windows", "linux"],
        },
      },
      required: ["projectRoot", "flowId"],
      additionalProperties: false,
    },
  },
  {
    name: "setup_record",
    description: "Record host-local progress for a DevNexus guided setup flow.",
    inputSchema: {
      type: "object",
      properties: {
        projectRoot: { type: "string" },
        flowId: { type: "string" },
        stepId: { type: "string" },
        status: {
          type: "string",
          enum: ["pending", "completed", "blocked", "skipped"],
        },
        note: { type: ["string", "null"] },
      },
      required: ["projectRoot", "flowId", "stepId", "status"],
      additionalProperties: false,
    },
  },
  {
    name: "target_cycle_list",
    description: "List recorded DevNexus target cycles without mutating state.",
    inputSchema: {
      type: "object",
      properties: {
        homePath: { type: "string" },
        detail: { type: "string", enum: ["summary", "full"], default: "summary" },
        project: { type: "string" },
        projectRoot: { type: "string" },
      },
      additionalProperties: false,
    },
  },
  {
    name: "target_cycle_record",
    description: "Record caller-reported DevNexus target cycle progress.",
    inputSchema: {
      type: "object",
      properties: {
        homePath: { type: "string" },
        detail: { type: "string", enum: ["summary", "full"], default: "summary" },
        project: { type: "string" },
        projectRoot: { type: "string" },
        cycleId: { type: "string" },
        runId: { type: "string" },
        status: {
          type: "string",
          enum: ["started", "dispatched", "completed", "blocked", "failed", "skipped"],
        },
        summary: { type: ["string", "null"] },
        eligibleWorkItemCount: { type: ["number", "null"] },
        workItems: {
          type: "array",
          items: {
            type: "object",
            properties: {
              componentId: { type: ["string", "null"] },
              id: { type: "string" },
              title: { type: ["string", "null"] },
              status: { type: ["string", "null"] },
              cycleStatus: {
                type: ["string", "null"],
                enum: [
                  "eligible",
                  "selected",
                  "dispatched",
                  "in_progress",
                  "completed",
                  "blocked",
                  "failed",
                  "skipped",
                  null,
                ],
              },
              agentProfileId: { type: ["string", "null"] },
              notes: {
                type: ["string", "null"],
                maxLength: maxNexusAutomationTargetCycleNoteLength,
              },
            },
            required: ["id"],
            additionalProperties: false,
          },
        },
        blockers: { type: "array", items: { type: "string" } },
        notes: {
          type: "array",
          items: {
            type: "string",
            maxLength: maxNexusAutomationTargetCycleNoteLength,
          },
        },
      },
      required: ["status"],
      additionalProperties: false,
    },
  },
  {
    name: "target_report",
    description: "Build a factual DevNexus target report from recorded target, cycle, run, and work-item facts.",
    inputSchema: {
      type: "object",
      properties: {
        homePath: { type: "string" },
        detail: { type: "string", enum: ["summary", "full"], default: "summary" },
        project: { type: "string" },
        projectRoot: { type: "string" },
      },
      additionalProperties: false,
    },
  },
  {
    name: "publication_feature_plan",
    description: "Build a read-only feature branch delivery branch plan from configured publication policy.",
    inputSchema: {
      type: "object",
      properties: {
        projectRoot: { type: "string" },
        componentId: { type: "string" },
        featureId: { type: "string" },
      },
      required: ["projectRoot"],
      additionalProperties: false,
    },
  },
  {
    name: "publication_feature_report",
    description: "Build a read-only feature branch delivery readiness report from configured policy and optional provider evidence.",
    inputSchema: {
      type: "object",
      properties: {
        projectRoot: { type: "string" },
        componentId: { type: "string" },
        featureId: { type: "string" },
        providerEvidence: {
          type: "array",
          items: { type: "object", additionalProperties: true },
        },
        fullMatrixBudgetAvailable: { type: "boolean" },
      },
      required: ["projectRoot"],
      additionalProperties: false,
    },
  },
  {
    name: "publication_feature_finalization",
    description: "Build a read-only feature finalization plan that separates review readiness from publication authority.",
    inputSchema: {
      type: "object",
      properties: {
        projectRoot: { type: "string" },
        componentId: { type: "string" },
        featureId: { type: "string" },
        providerEvidence: {
          type: "array",
          items: { type: "object", additionalProperties: true },
        },
        fullMatrixBudgetAvailable: { type: "boolean" },
      },
      required: ["projectRoot"],
      additionalProperties: false,
    },
  },
  ...nexusPublicationMcpTools,
  {
    name: "review_plan",
    description: "Build a read-only component review plan from review policy, local authorization, and optional provider evidence.",
    inputSchema: {
      type: "object",
      properties: {
        projectRoot: { type: "string" },
        componentId: { type: "string" },
        branchRole: { type: "string" },
        paths: {
          type: "array",
          items: { type: "string" },
        },
        labels: {
          type: "array",
          items: { type: "string" },
        },
        requestedAction: { type: "string" },
        branchName: { type: "string" },
        headSha: { type: "string" },
        localAuthorization: {
          type: "object",
          properties: {
            authorized: { type: "boolean" },
            authorizedAt: { type: "string" },
            branchName: { type: "string" },
            headSha: { type: "string" },
            requestedAction: { type: "string" },
            summary: { type: "string" },
          },
          additionalProperties: false,
        },
        providerEvidence: {
          type: "array",
          items: { type: "object", additionalProperties: true },
        },
      },
      required: ["projectRoot"],
      additionalProperties: false,
    },
  },
  {
    name: "current_agent_adopt",
    description: "Create or reuse DevNexus agent-launch context for the current coordinator without spawning nested model execution.",
    inputSchema: {
      type: "object",
      properties: {
        homePath: { type: "string" },
        project: { type: "string" },
        projectRoot: { type: "string" },
        runId: { type: "string" },
        owner: { type: ["string", "null"] },
        coordinatorLoop: { type: "boolean" },
        runIdPrefix: { type: "string" },
      },
      additionalProperties: false,
    },
  },
  {
    name: "current_agent_heartbeat",
    description: "Renew the current coordinator's authority-backed work-item claim lease.",
    inputSchema: {
      type: "object",
      properties: {
        homePath: { type: "string" },
        project: { type: "string" },
        projectRoot: { type: "string" },
        leaseDurationMs: { type: "number" },
      },
      additionalProperties: false,
    },
  },
  {
    name: "current_agent_record",
    description: "Record the current coordinator's adopted DevNexus run result and release its adoption lock.",
    inputSchema: {
      type: "object",
      properties: {
        homePath: { type: "string" },
        project: { type: "string" },
        projectRoot: { type: "string" },
        runId: { type: "string" },
        result: {
          type: "object",
          properties: {
            status: {
              type: "string",
              enum: ["completed", "blocked", "failed", "skipped"],
            },
            summary: { type: "string" },
            commitIds: { type: "array", items: { type: "string" } },
            verification: {
              type: "array",
              items: {
                type: "object",
                properties: {
                  command: { type: "string" },
                  status: {
                    type: "string",
                    enum: ["passed", "failed", "not_run"],
                  },
                  summary: { type: ["string", "null"] },
                },
                required: ["command"],
                additionalProperties: false,
              },
            },
            publicationDecision: {
              type: "object",
              properties: {
                type: {
                  type: "string",
                  enum: [
                    "not_decided",
                    "local_only",
                    "direct_integration",
                    "review_handoff",
                    "blocked",
                  ],
                },
                targetBranch: { type: ["string", "null"] },
                remote: { type: ["string", "null"] },
                prUrl: { type: ["string", "null"] },
                reason: { type: ["string", "null"] },
              },
              required: ["type"],
              additionalProperties: false,
            },
            error: { type: ["string", "null"] },
          },
          required: ["status", "summary"],
          additionalProperties: false,
        },
      },
      required: ["runId", "result"],
      additionalProperties: false,
    },
  },
  {
    name: "worktree_prepare",
    description: "Prepare an isolated Git worktree and branch for manual parallel agent work. Returns a compact summary with paths to generated context files.",
    inputSchema: {
      type: "object",
      properties: {
        homePath: { type: "string" },
        project: { type: "string" },
        projectRoot: { type: "string" },
        currentPath: { type: "string" },
        componentId: { type: "string" },
        projectMeta: { type: "boolean" },
        workItemId: { type: ["string", "null"] },
        workItemTitle: { type: ["string", "null"] },
        topic: { type: ["string", "null"] },
        branchName: { type: "string" },
        worktreeName: { type: "string" },
        baseRef: { type: ["string", "null"] },
        featureId: { type: ["string", "null"] },
        featureChange: { type: ["string", "null"] },
        featureParentBranch: { type: ["string", "null"] },
        featureStackPosition: { type: "number" },
        branchIntent: { type: ["string", "null"] },
        hostId: { type: ["string", "null"] },
        agentId: { type: ["string", "null"] },
        workerAgentProvider: { type: ["string", "null"] },
        writeScope: { type: "array", items: { type: "string" } },
        leaseNotes: { type: "array", items: { type: "string" } },
      },
      additionalProperties: false,
    },
  },
  {
    name: "coordination_status",
    description: "Report advisory shared coordination status for a component worktree and optional work item.",
    inputSchema: {
      type: "object",
      properties: {
        homePath: { type: "string" },
        detail: { type: "string", enum: ["summary", "full"], default: "summary" },
        project: { type: "string" },
        projectRoot: { type: "string" },
        componentId: { type: "string" },
        workItemId: { type: "string" },
        trackerId: { type: "string" },
        trackerRole: { type: "string" },
        currentPath: { type: "string" },
      },
      additionalProperties: false,
    },
  },
  {
    name: "coordination_start",
    description: "Start or adopt an interactive DevNexus worktree flow after checking coordination status, active leases, and authority.",
    inputSchema: {
      type: "object",
      properties: {
        homePath: { type: "string" },
        detail: { type: "string", enum: ["summary", "full"], default: "summary" },
        project: { type: "string" },
        projectRoot: { type: "string" },
        componentId: { type: "string" },
        projectMeta: { type: "boolean" },
        workItemId: { type: "string" },
        trackerId: { type: "string" },
        trackerRole: { type: "string" },
        currentPath: { type: "string" },
        topic: { type: ["string", "null"] },
        branchName: { type: "string" },
        worktreeName: { type: "string" },
        baseRef: { type: ["string", "null"] },
        dryRun: { type: "boolean" },
        hostId: { type: ["string", "null"] },
        agentId: { type: ["string", "null"] },
        workerAgentProvider: { type: ["string", "null"] },
        writeScope: { type: "array", items: { type: "string" } },
        leaseNotes: { type: "array", items: { type: "string" } },
      },
      additionalProperties: false,
    },
  },
  {
    name: "coordination_handoff",
    description: "Record an advisory structured coordination handoff. Provider comment handoffs are safe from component worktrees when the selected provider tracker opts in with communication.coordinationHandoffs=comment; local or silent handoffs require a workspace/meta currentPath. Pass repositoryPath separately when Git facts come from a component source worktree.",
    inputSchema: {
      type: "object",
      properties: {
        homePath: { type: "string" },
        project: { type: "string" },
        projectRoot: { type: "string" },
        currentPath: { type: "string" },
        repositoryPath: { type: "string" },
        componentId: { type: "string" },
        workItemId: { type: "string" },
        trackerId: { type: "string" },
        trackerRole: { type: "string" },
        status: {
          type: "string",
          enum: ["working", "ready", "blocked", "merged"],
        },
        hostId: { type: "string" },
        agentId: { type: "string" },
        changedAreas: { type: "array", items: { type: "string" } },
        decisions: { type: "array", items: { type: "string" } },
        verificationSummary: { type: ["string", "null"] },
        integrationPreference: { type: ["string", "null"] },
        qualityDelta: {
          type: "object",
          description:
            "Optional local quality delta payload from a component or plugin check.",
          additionalProperties: true,
        },
        note: { type: ["string", "null"] },
      },
      required: ["workItemId", "status"],
      additionalProperties: false,
    },
  },
  {
    name: "coordination_integrate",
    description: "Build a read-only integration plan from related handoff branches, Git merge analysis, and recorded decisions.",
    inputSchema: {
      type: "object",
      properties: {
        homePath: { type: "string" },
        project: { type: "string" },
        projectRoot: { type: "string" },
        currentPath: { type: "string" },
        componentId: { type: "string" },
        workItemId: { type: "string" },
        trackerId: { type: "string" },
        trackerRole: { type: "string" },
        targetBranch: { type: "string" },
        fetch: { type: "boolean" },
      },
      additionalProperties: false,
    },
  },
  {
    name: "coordination_cleanup_execute",
    description: "Remove one safe DevNexus cleanup-plan candidate and update matching worktree lease metadata.",
    inputSchema: {
      type: "object",
      properties: {
        homePath: { type: "string" },
        project: { type: "string" },
        projectRoot: { type: "string" },
        componentId: { type: "string" },
        candidateId: { type: "string" },
        includeProjectMeta: { type: "boolean" },
        targetBranch: { type: "string" },
        keepBranch: { type: "boolean" },
        force: { type: "boolean" },
        forceReason: { type: ["string", "null"], maxLength: 500 },
        rescueBranch: { type: "string" },
        rescueReason: { type: ["string", "null"], maxLength: 500 },
        archiveSummary: { type: "string", maxLength: 1000 },
        archiveUrl: { type: ["string", "null"], maxLength: 1000 },
      },
      required: ["candidateId"],
      additionalProperties: false,
    },
  },
  {
    name: "coordination_request",
    description: "Draft a provider-neutral external coordination request and summarize mocked provider responses without live provider posting.",
    inputSchema: {
      type: "object",
      properties: {
        homePath: { type: "string" },
        project: { type: "string" },
        projectRoot: { type: "string" },
        currentPath: { type: "string" },
        componentId: { type: "string" },
        workItemId: { type: "string" },
        trackerId: { type: "string" },
        trackerRole: { type: "string" },
        intent: {
          type: "string",
          enum: ["approval", "feedback", "choice", "review"],
        },
        question: { type: ["string", "null"] },
        note: { type: ["string", "null"] },
        target: { type: ["string", "null"] },
        hostId: { type: "string" },
        agentId: { type: "string" },
        responseStatus: {
          type: "string",
          enum: [
            "waiting",
            "answered",
            "approved",
            "changes_requested",
            "timed_out",
            "blocked",
          ],
        },
        responseSummary: { type: ["string", "null"] },
        responder: { type: ["string", "null"] },
        requestedChanges: { type: "array", items: { type: "string" } },
      },
      required: ["intent"],
      additionalProperties: false,
    },
  },
  {
    name: "host_check",
    description: "Run a read-only local or mocked remote host capability check.",
    inputSchema: {
      type: "object",
      properties: {
        projectRoot: { type: "string" },
        hostId: { type: "string" },
        mode: { type: "string", enum: ["local", "mock-remote"] },
        mockFacts: { type: "object" },
      },
      required: ["projectRoot"],
      additionalProperties: false,
    },
  },
  {
    name: "remote_execution_request_create",
    description: "Create a draft/local durable remote execution request without running commands.",
    inputSchema: {
      type: "object",
      properties: {
        projectRoot: { type: "string" },
        componentId: { type: "string" },
        workItemId: { type: ["string", "null"] },
        requestingHostId: { type: "string" },
        requestingAgentId: { type: ["string", "null"] },
        targetHostId: { type: ["string", "null"] },
        requiredCapabilities: { type: "array", items: { type: "string" } },
        runnerProfileId: { type: "string" },
        repository: { type: "string" },
        ref: { type: "string" },
        commandProfileId: { type: "string" },
        timeoutMs: { type: "number" },
        expectedArtifacts: { type: "array", items: { type: "string" } },
        mutationClass: {
          type: "string",
          enum: ["none", "verification", "project_local", "live_runtime", "destructive"],
        },
        initialStatus: {
          type: "string",
          enum: [
            "queued",
            "accepted",
            "running",
            "completed",
            "failed",
            "blocked",
            "timed_out",
            "cancelled",
          ],
        },
        attachmentRefs: { type: "array", items: { type: "object" } },
      },
      required: [
        "projectRoot",
        "requestingHostId",
        "runnerProfileId",
        "repository",
        "ref",
        "commandProfileId",
        "timeoutMs",
        "mutationClass",
      ],
      additionalProperties: false,
    },
  },
  {
    name: "remote_execution_result_record",
    description: "Record a draft/local remote execution result without running commands.",
    inputSchema: {
      type: "object",
      properties: {
        projectRoot: { type: "string" },
        requestId: { type: "string" },
        status: {
          type: "string",
          enum: [
            "queued",
            "accepted",
            "running",
            "completed",
            "failed",
            "blocked",
            "timed_out",
            "cancelled",
          ],
        },
        hostId: { type: "string" },
        runnerProfileId: { type: "string" },
        actualRef: { type: ["string", "null"] },
        actualCommit: { type: ["string", "null"] },
        commands: { type: "array", items: { type: "string" } },
        exitCode: { type: ["number", "null"] },
        verificationOutcome: {
          type: "string",
          enum: ["passed", "failed", "not_run", "blocked", "timed_out", "cancelled"],
        },
        outputTail: {
          type: ["string", "null"],
          maxLength: maxNexusRemoteExecutionOutputTailLength,
        },
        artifactRefs: { type: "array", items: { type: "string" } },
        cleanupStatus: {
          type: "string",
          enum: ["not_required", "completed", "failed", "blocked", "unknown"],
        },
        blockerSafetyReason: { type: ["string", "null"] },
      },
      required: [
        "projectRoot",
        "requestId",
        "status",
        "hostId",
        "runnerProfileId",
        "verificationOutcome",
        "cleanupStatus",
      ],
      additionalProperties: false,
    },
  },
  {
    name: "remote_execution_result_get",
    description: "Read a draft/local remote execution request and recorded result by request id.",
    inputSchema: {
      type: "object",
      properties: {
        projectRoot: { type: "string" },
        requestId: { type: "string" },
      },
      required: ["projectRoot", "requestId"],
      additionalProperties: false,
    },
  },
  {
    name: "remote_execution_ssh_plan",
    description: "Build a sanitized SSH/Tailscale execution plan for a recorded request without running network commands.",
    inputSchema: {
      type: "object",
      properties: {
        projectRoot: { type: "string" },
        requestId: { type: "string" },
        homePath: { type: "string" },
      },
      required: ["projectRoot", "requestId"],
      additionalProperties: false,
    },
  },
  {
    name: "remote_execution_run",
    description: "Run a recorded verification-only SSH remote execution request through an approved home command profile and record the result.",
    inputSchema: {
      type: "object",
      properties: {
        projectRoot: { type: "string" },
        requestId: { type: "string" },
        homePath: { type: "string" },
      },
      required: ["projectRoot", "requestId"],
      additionalProperties: false,
    },
  },
  {
    name: "work_item_create",
    description: "Create a work item through the configured DevNexus work tracker.",
    inputSchema: {
      type: "object",
      properties: {
        homePath: { type: "string" },
        project: { type: "string" },
        projectRoot: { type: "string" },
        componentId: { type: "string" },
        trackerId: { type: "string" },
        title: { type: "string" },
        description: { type: ["string", "null"] },
        status: { type: "string" },
        labels: { type: "array", items: { type: "string" } },
        assignees: { type: "array", items: { type: "string" } },
        milestone: { type: ["string", "null"] },
      },
      required: ["title"],
      additionalProperties: false,
    },
  },
  {
    name: "work_item_discovery_status",
    description: "Report read-only tracker discovery status and provider readability without mutating tracker or provider state.",
    inputSchema: {
      type: "object",
      properties: {
        homePath: { type: "string" },
        project: { type: "string" },
        projectRoot: { type: "string" },
        detail: {
          type: "string",
          enum: ["summary", "full"],
          default: "summary",
          description: "summary returns the compact default result envelope; full returns the complete discovery status tree.",
        },
      },
      additionalProperties: false,
    },
  },
  {
    name: "work_item_claim_next",
    description: "Claim the next eligible work item through the configured DevNexus work tracker.",
    inputSchema: {
      type: "object",
      properties: {
        homePath: { type: "string" },
        project: { type: "string" },
        projectRoot: { type: "string" },
        componentId: { type: "string" },
        trackerId: { type: "string" },
        mode: { type: "string", enum: ["default", "discovery"] },
        hostId: { type: "string" },
        agentId: { type: ["string", "null"] },
        ownerId: { type: ["string", "null"] },
        leaseDurationMs: { type: "number" },
        staleClaimPolicy: {
          type: "string",
          enum: ["report", "reclaim"],
        },
      },
      required: ["hostId"],
      additionalProperties: false,
    },
  },
  {
    name: "work_item_claim_release",
    description: "Release an authority-backed work item claim by lease token.",
    inputSchema: {
      type: "object",
      properties: {
        homePath: { type: "string" },
        project: { type: "string" },
        projectRoot: { type: "string" },
        componentId: { type: "string" },
        trackerId: { type: "string" },
        itemId: { type: "string" },
        leaseToken: { type: "string" },
        fencingToken: { type: "number" },
      },
      required: ["itemId", "leaseToken"],
      additionalProperties: false,
    },
  },
  {
    name: "work_item_list",
    description: "List work items through the configured DevNexus work tracker.",
    inputSchema: {
      type: "object",
      properties: {
        homePath: { type: "string" },
        project: { type: "string" },
        projectRoot: { type: "string" },
        componentId: { type: "string" },
        trackerId: { type: "string" },
        status: {
          oneOf: [
            { type: "string" },
            { type: "array", items: { type: "string" } },
          ],
        },
        labels: { type: "array", items: { type: "string" } },
        assignees: { type: "array", items: { type: "string" } },
        search: { type: "string" },
        limit: { type: "number", default: 50, maximum: 100 },
        detail: { type: "string", enum: ["summary", "full"], default: "summary" },
      },
      additionalProperties: false,
    },
  },
  {
    name: "work_item_get",
    description: "Get a work item through the configured DevNexus work tracker.",
    inputSchema: {
      type: "object",
      properties: {
        homePath: { type: "string" },
        project: { type: "string" },
        projectRoot: { type: "string" },
        componentId: { type: "string" },
        trackerId: { type: "string" },
        id: { type: "string" },
        provider: { type: "string" },
        externalRef: { type: "object" },
        ref: { type: "object" },
      },
      additionalProperties: false,
    },
  },
  {
    name: "work_item_update",
    description: "Update a work item through the configured DevNexus work tracker.",
    inputSchema: {
      type: "object",
      properties: {
        homePath: { type: "string" },
        project: { type: "string" },
        projectRoot: { type: "string" },
        currentPath: { type: "string" },
        componentId: { type: "string" },
        trackerId: { type: "string" },
        id: { type: "string" },
        provider: { type: "string" },
        externalRef: { type: "object" },
        ref: { type: "object" },
        title: { type: "string" },
        description: { type: ["string", "null"] },
        status: { type: "string" },
        labels: { type: "array", items: { type: "string" } },
        assignees: { type: "array", items: { type: "string" } },
        milestone: { type: ["string", "null"] },
      },
      additionalProperties: false,
    },
  },
  {
    name: "work_item_comment",
    description: "Add a comment to a work item through the configured DevNexus work tracker.",
    inputSchema: {
      type: "object",
      properties: {
        homePath: { type: "string" },
        project: { type: "string" },
        projectRoot: { type: "string" },
        currentPath: { type: "string" },
        componentId: { type: "string" },
        trackerId: { type: "string" },
        id: { type: "string" },
        provider: { type: "string" },
        externalRef: { type: "object" },
        ref: { type: "object" },
        body: { type: "string" },
      },
      required: ["body"],
      additionalProperties: false,
    },
  },
  {
    name: "work_item_set_status",
    description: "Set a work item's status through the configured DevNexus work tracker.",
    inputSchema: {
      type: "object",
      properties: {
        homePath: { type: "string" },
        project: { type: "string" },
        projectRoot: { type: "string" },
        currentPath: { type: "string" },
        componentId: { type: "string" },
        trackerId: { type: "string" },
        id: { type: "string" },
        provider: { type: "string" },
        externalRef: { type: "object" },
        ref: { type: "object" },
        status: { type: "string" },
      },
      required: ["status"],
      additionalProperties: false,
    },
  },
  {
    name: "work_item_link",
    description: "Link a logical work item to a configured tracker reference.",
    inputSchema: {
      type: "object",
      properties: {
        homePath: { type: "string" },
        project: { type: "string" },
        projectRoot: { type: "string" },
        componentId: { type: "string" },
        logicalItemId: { type: "string" },
        trackerId: { type: "string" },
        provider: { type: "string" },
        host: { type: ["string", "null"] },
        repositoryId: { type: ["string", "null"] },
        repositoryOwner: { type: ["string", "null"] },
        repositoryName: { type: ["string", "null"] },
        projectId: { type: ["string", "null"] },
        boardId: { type: ["string", "null"] },
        itemId: { type: "string" },
        itemNumber: { type: ["number", "null"] },
        itemKey: { type: ["string", "null"] },
        nodeId: { type: ["string", "null"] },
        webUrl: { type: ["string", "null"] },
        observedAt: { type: ["string", "null"] },
      },
      required: ["logicalItemId", "trackerId", "itemId"],
      additionalProperties: false,
    },
  },
  {
    name: "work_item_show_links",
    description: "Show tracker references linked to one logical work item.",
    inputSchema: {
      type: "object",
      properties: {
        homePath: { type: "string" },
        project: { type: "string" },
        projectRoot: { type: "string" },
        componentId: { type: "string" },
        logicalItemId: { type: "string" },
      },
      required: ["logicalItemId"],
      additionalProperties: false,
    },
  },
  {
    name: "work_item_unlink",
    description: "Unlink a tracker reference from one logical work item and record audit metadata.",
    inputSchema: {
      type: "object",
      properties: {
        homePath: { type: "string" },
        project: { type: "string" },
        projectRoot: { type: "string" },
        componentId: { type: "string" },
        logicalItemId: { type: "string" },
        trackerId: { type: "string" },
        itemId: { type: "string" },
        reason: { type: ["string", "null"] },
      },
      required: ["logicalItemId", "trackerId", "itemId"],
      additionalProperties: false,
    },
  },
  {
    name: "work_item_sync_plan",
    description: "Build a mutation-free dry-run plan for syncing work items from one configured tracker to another.",
    inputSchema: {
      type: "object",
      properties: {
        homePath: { type: "string" },
        project: { type: "string" },
        projectRoot: { type: "string" },
        componentId: { type: "string" },
        sourceTrackerId: { type: "string" },
        targetTrackerId: { type: "string" },
        direction: { type: "string", enum: ["source_to_target"] },
        filters: { type: "object" },
        fieldSet: {
          type: "array",
          items: {
            type: "string",
            enum: [
              "title",
              "description",
              "status",
              "labels",
              "assignees",
              "milestone",
            ],
          },
        },
        commentPolicy: { type: "string", enum: ["ignore", "plan"] },
        statusMapping: { type: "object" },
        conflictPolicy: {
          type: "string",
          enum: ["block", "source_wins", "target_wins"],
        },
        writePolicy: { type: "object" },
      },
      required: ["sourceTrackerId", "targetTrackerId"],
      additionalProperties: false,
    },
  },
  {
    name: "work_item_import_plan",
    description: "Build a strictly read-only inbound GitHub-to-local work-item import plan.",
    inputSchema: {
      type: "object",
      properties: {
        homePath: { type: "string" },
        project: { type: "string" },
        projectRoot: { type: "string" },
        componentId: { type: "string" },
        sourceTrackerId: { type: "string" },
        targetTrackerId: { type: "string" },
        direction: { type: "string", enum: ["external_to_local"] },
        filters: { type: "object" },
        fieldSet: {
          type: "array",
          items: {
            type: "string",
            enum: [
              "title",
              "description",
              "status",
              "labels",
              "assignees",
              "milestone",
            ],
          },
        },
        statusMapping: { type: "object" },
        conflictPolicy: {
          type: "string",
          enum: ["block", "source_wins", "target_wins"],
        },
        writePolicy: { type: "object" },
        fingerprints: {
          type: "array",
          items: {
            type: "string",
            enum: ["external_ref", "web_url", "title"],
          },
        },
      },
      required: ["sourceTrackerId", "targetTrackerId"],
      additionalProperties: false,
    },
  },
  {
    name: "work_item_import_execute",
    description: "Execute a policy-gated inbound GitHub-to-local work-item import without provider writes.",
    inputSchema: {
      type: "object",
      properties: {
        homePath: { type: "string" },
        project: { type: "string" },
        projectRoot: { type: "string" },
        componentId: { type: "string" },
        sourceTrackerId: { type: "string" },
        targetTrackerId: { type: "string" },
        direction: { type: "string", enum: ["external_to_local"] },
        filters: { type: "object" },
        fieldSet: {
          type: "array",
          items: {
            type: "string",
            enum: [
              "title",
              "description",
              "status",
              "labels",
              "assignees",
              "milestone",
            ],
          },
        },
        statusMapping: { type: "object" },
        conflictPolicy: {
          type: "string",
          enum: ["block", "source_wins", "target_wins"],
        },
        writePolicy: { type: "object" },
        fingerprints: {
          type: "array",
          items: {
            type: "string",
            enum: ["external_ref", "web_url", "title"],
          },
        },
      },
      required: [
        "sourceTrackerId",
        "targetTrackerId",
        "direction",
        "writePolicy",
      ],
      additionalProperties: false,
    },
  },
  {
    name: "work_item_sync_execute",
    description: "Execute an explicitly policy-gated one-way local-to-GitHub work-item sync and record a run summary.",
    inputSchema: {
      type: "object",
      properties: {
        homePath: { type: "string" },
        project: { type: "string" },
        projectRoot: { type: "string" },
        componentId: { type: "string" },
        sourceTrackerId: { type: "string" },
        targetTrackerId: { type: "string" },
        direction: { type: "string", enum: ["source_to_target"] },
        filters: { type: "object" },
        fieldSet: {
          type: "array",
          items: {
            type: "string",
            enum: [
              "title",
              "description",
              "status",
              "labels",
              "assignees",
              "milestone",
            ],
          },
        },
        commentPolicy: { type: "string", enum: ["ignore", "plan"] },
        statusMapping: { type: "object" },
        conflictPolicy: {
          type: "string",
          enum: ["block", "source_wins", "target_wins"],
        },
        writePolicy: { type: "object" },
        recordRun: { type: "boolean" },
      },
      required: ["sourceTrackerId", "targetTrackerId"],
      additionalProperties: false,
    },
  },
];

export function listDevNexusMcpTools(): McpTool[] {
  return providerCompatibleMcpTools(devNexusMcpTools);
}
