export function usage(): string {
  return [
    "Usage:",
    "  dev-nexus --help",
    "  dev-nexus mcp-stdio",
    "  dev-nexus mcp-gateway-stdio",
    "  dev-nexus home init [home-path] [options]",
    "  dev-nexus workspace create <name> [options]",
    "  dev-nexus workspace init [workspace-root] [options]",
    "  dev-nexus workspace setup [workspace-root] [options]",
    "  dev-nexus workspace component add <workspace-root> [options]",
    "  dev-nexus workspace import <source-root> [options]",
    "  dev-nexus workspace list [options]",
    "  dev-nexus workspace status <workspace-id-or-root> [options]",
    "  dev-nexus workspace hosting status <workspace-root> [options]",
    "  dev-nexus workspace hosting plan <workspace-root> [options]",
    "  dev-nexus workspace hosting apply <workspace-root> [options]",
    "  dev-nexus workspace mcp refresh <workspace-root> [options]",
    "  dev-nexus workspace mcp budget <workspace-root> [options]",
    "  dev-nexus workspace plugin refresh <workspace-root> --from <package|path> [options]",
    "  dev-nexus workspace agent-projection cleanup <workspace-root> [options]",
    "  dev-nexus workspace tracker configure <workspace> --provider <provider> [options]",
    "  dev-nexus workspace tracker link <workspace> --tracker-project-id <id> [options]",
    "  dev-nexus setup list [options]",
    "  dev-nexus setup plan <workspace-root> <flow-id> [options]",
    "  dev-nexus setup check <workspace-root> <flow-id> [options]",
    "  dev-nexus setup readiness <workspace-root> [options]",
    "  dev-nexus setup record <workspace-root> <flow-id> <step-id> --status <status> [options]",
    "  dev-nexus diagnostics cli-version-skew [options]",
    "  dev-nexus host check <workspace-root> [options]",
    "  dev-nexus coordination status <workspace-root> [options]",
    "  dev-nexus coordination handoff <workspace-root> <work-item-id> --status <status> [options]",
    "  dev-nexus coordination integrate <workspace-root> [options]",
    "  dev-nexus coordination cleanup-plan <workspace-root> [options]",
    "  dev-nexus coordination request <workspace-root> --intent <intent> (--question <text>|--note <text>) [options]",
    "  dev-nexus remote-execution request create <workspace-root> [options]",
    "  dev-nexus remote-execution result record <workspace-root> <request-id> [options]",
    "  dev-nexus remote-execution result get <workspace-root> <request-id> [options]",
    "  dev-nexus remote-execution ssh-plan <workspace-root> <request-id> [options]",
    "  dev-nexus worktree prepare <workspace-root> [options]",
    "  dev-nexus publication branch-push <workspace-root> --branch <branch> [options]",
    "  dev-nexus publication pull-request upsert <workspace-root> --head <branch> --title <title> [options]",
    "  dev-nexus publication pull-request merge <workspace-root> --number <number> [options]",
    "  dev-nexus publication green-main plan <workspace-root> --pr <number> --checks-file <json-file> [options]",
    "  dev-nexus publication evidence normalize <json-file> [options]",
    "  dev-nexus publication merge-queue-readiness <workspace-root> [options]",
    "  dev-nexus publication train-readiness <workspace-root> [options]",
    "  dev-nexus publication candidate-plan <workspace-root> [options]",
    "  dev-nexus quick-fix plan <workspace-root> --work-item <id> [options]",
    "  dev-nexus quick-fix start <workspace-root> --work-item <id> [options]",
    "  dev-nexus quick-fix finish <workspace-root> --work-item <id> --pr-url <url> --merge-commit <sha> --verification <text> [options]",
    "  dev-nexus work-item create <workspace-root> --title <title> [options]",
    "  dev-nexus work-item discovery-status <workspace-root> [options]",
    "  dev-nexus work-item claim-next <workspace-root> --host <id> [options]",
    "  dev-nexus work-item list <workspace-root> [options]",
    "  dev-nexus work-item get <workspace-root> <work-item-id> [options]",
    "  dev-nexus work-item update <workspace-root> <work-item-id> [options]",
    "  dev-nexus work-item comment <workspace-root> <work-item-id> --body <text> [options]",
    "  dev-nexus work-item set-status <workspace-root> <work-item-id> --status <status> [options]",
    "  dev-nexus work-item link <workspace-root> <logical-item-id> --tracker <id> --item-id <id> [options]",
    "  dev-nexus work-item show-links <workspace-root> <logical-item-id> [options]",
    "  dev-nexus work-item unlink <workspace-root> <logical-item-id> --tracker <id> --item-id <id> [options]",
    "  dev-nexus work-item import-plan <workspace-root> --source-tracker <github-id> --target-tracker <local-id> [options]",
    "  dev-nexus work-item import-execute <workspace-root> --source-tracker <github-id> --target-tracker <local-id> --direction external_to_local --credentials available [options]",
    "  dev-nexus work-item sync-plan <workspace-root> --source-tracker <id> --target-tracker <id> [options]",
    "  dev-nexus work-item sync-execute <workspace-root> --source-tracker <id> --target-tracker <id> --credentials available [options]",
    "  dev-nexus ci-failure-intake plan <workspace-root> --input <json-file> [options]",
    "  dev-nexus automation status <workspace-root> [options]",
    "  dev-nexus automation eligible-work <workspace-root> [options]",
    "  dev-nexus automation agent-profiles <workspace-root> [options]",
    "  dev-nexus automation app-server-probe <workspace-root> [options]",
    "  dev-nexus automation enqueue <workspace-root> --title <title> [options]",
    "  dev-nexus automation heartbeat prepare <workspace-root> [options]",
    "  dev-nexus automation target-cycle list <workspace-root> [options]",
    "  dev-nexus automation target-cycle record <workspace-root> --status <status> [options]",
    "  dev-nexus automation target-report <workspace-root> [options]",
    "  dev-nexus automation run-once <workspace-root> [--command <command>] [options]",
    "  dev-nexus automation schedule <workspace-root> [--command <command>] [options]",
    "  dev-nexus automation coordinator-loop <workspace-root> [--command <command>] [options]",
    "  dev-nexus automation current-agent adopt <workspace-root> [options]",
    "  dev-nexus automation current-agent record <workspace-root> --run-id <id> --status <status> --summary <text> [options]",
    "",
    "Options for home init:",
    "  --projects-root <path>",
    "  --workspaces-root <path>",
    "  --json",
    "",
    "Options for workspace commands:",
    "  --home <path>             defaults to DEV_NEXUS_HOME or ~/.dev-nexus",
    "  --json",
    "",
    "Options for workspace hosting commands:",
    "  --home <path>",
    "  --json",
    "",
    "Options for workspace create:",
    "  --home <path>",
    "  --root <path>",
    "  --from <git-url>",
    "  --git-init",
    "  --tracker-project-id <id>",
    "  --json",
    "",
    "Options for workspace init/setup:",
    "  --home <path>",
    "  --answers <json-file>     setup answers for non-interactive automation",
    "  --dry-run                 preview only; omit to apply local setup writes",
    "  --json",
    "",
    "Options for workspace component add:",
    "  --answers <json-file>     component answers with one or more components",
    "  --home <path>",
    "  --dry-run                 preview only; omit to update local workspace config/scaffold",
    "  --json",
    "",
    "Options for workspace import:",
    "  --home <path>",
    "  --workspace-root <path>",
    "  --name <name>",
    "  --tracker-project-id <id>",
    "  --json",
    "",
    "Options for workspace mcp refresh:",
    "  --agent <agent>           repeatable; defaults to workspace mcp.agentTargets or codex",
    "  --dry-run                 resolve targets and exposure policy without writing config",
    "  --json",
    "",
    "Options for workspace mcp budget:",
    "  --agent <agent>           repeatable; defaults to active MCP targets",
    "  --top <count>             number of top servers and tools to include; default 10",
    "  --json",
    "",
    "Options for workspace plugin refresh:",
    "  --from <package|path>     npm package name, local package directory, or module file",
    "  --export <name>           plugin config export; auto-detected when unambiguous",
    "  --skills-export <name>    skill definitions export; package skills/ is also discovered",
    "  --agent <agent>           repeatable; limit materialization to active agent targets",
    "  --component <component>   repeatable; pass target component ids to plugin factories",
    "  --dry-run                 resolve and validate without writing config or projections",
    "  --json",
    "",
    "Options for workspace agent-projection cleanup:",
    "  --apply                   remove only cleanup-safe stale generated provider support",
    "  --dry-run                 preview only; default when --apply is omitted",
    "  --json",
    "",
    "Options for workspace tracker configure:",
    "  --home <path>",
    "  --provider <local|github|gitlab|jira>",
    "  --host <host>",
    "  --repository-owner <owner>",
    "  --repository-name <name>",
    "  --repository-id <id>",
    "  --project-key <key>",
    "  --issue-type <type>",
    "  --store-path <path>",
    "  --json",
    "",
    "Options for workspace tracker link:",
    "  --home <path>",
    "  --tracker-project-id <id>",
    "  --json",
    "",
    "Options for setup:",
    "  --platform <auto|macos|windows|linux>",
    "  --status <pending|completed|blocked|skipped>",
    "  --note <text>",
    "  --json",
    "",
    "Options for diagnostics cli-version-skew:",
    "  --installed-help-file <path>  help text to inspect; defaults to this CLI help",
    "  --installed-command <command> command to inspect with --help, such as dev-nexus",
    "  --expected-file <path>        documentation file to scan; repeatable",
    "  --expected-command <command>  documented command to require; repeatable",
    "  --package-version <version>   installed package version to report",
    "  --json",
    "",
    "Options for host check:",
    "  --host <id>               configured project host id; defaults to local host",
    "  --mock-remote             use mocked remote facts instead of local command probes",
    "  --mock-facts <json-file>  mocked remote facts for tests and dry runs",
    "  --json",
    "",
    "Options for coordination status:",
    "  --component <id>          defaults to component inferred from --worktree or current directory",
    "  --work-item <id>",
    "  --tracker <id>            coordination tracker id; defaults to role coordination, then component default",
    "  --tracker-role <role>     coordination tracker role such as coordination or external_feedback",
    "  --worktree <path>         git worktree or source checkout used for status",
    "  --json",
    "",
    "Options for coordination handoff:",
    "  --component <id>          defaults to component inferred from --worktree or current directory",
    "  --status <working|ready|blocked|merged>",
    "  --tracker <id>            coordination tracker id; defaults to role coordination, then component default",
    "  --tracker-role <role>     coordination tracker role such as coordination or external_feedback",
    "  --host <id>",
    "  --agent <id>",
    "  --changed-area <path>      repeatable",
    "  --decision <text>          repeatable",
    "  --verification <text>",
    "  --integration-preference <text>",
    "  --note <text>",
    "  --worktree <path>         git worktree or source checkout used for status",
    "  --json",
    "",
    "Options for coordination integrate:",
    "  --component <id>          defaults to component inferred from --worktree or current directory",
    "  --work-item <id>",
    "  --tracker <id>            coordination tracker id; defaults to role coordination, then component default",
    "  --tracker-role <role>     coordination tracker role such as coordination or external_feedback",
    "  --target-branch <branch>  defaults to component or automation publication target",
    "  --fetch                   fetch configured remote when automation safety allows host mutation",
    "  --worktree <path>         git worktree or source checkout used for planning",
    "  --json",
    "",
    "Options for coordination cleanup-plan:",
    "  --component <id>          defaults to the primary component",
    "  --include-workspace-meta  also scan workspace-meta worktrees and branches",
    "  --target-branch <branch>  defaults to component or workspace publication target",
    "  --json",
    "",
    "Options for coordination request:",
    "  --component <id>          defaults to component inferred from --worktree or current directory",
    "  --work-item <id>",
    "  --tracker <id>            request record tracker id; defaults to role external_feedback, coordination, then component default",
    "  --tracker-role <role>     request record tracker role such as external_feedback or coordination",
    "  --intent <approval|feedback|choice|review>",
    "  --question <text>",
    "  --note <text>",
    "  --target <target>         examples: github-issue:1, github-pr:2, gitlab-issue:3, gitlab-mr:4, jira:KEY-5",
    "  --host <id>",
    "  --agent <id>",
    "  --response-status <waiting|answered|approved|changes_requested|timed_out|blocked>",
    "  --response-summary <text>",
    "  --responder <id>",
    "  --requested-change <text>  repeatable",
    "  --worktree <path>         git worktree or source checkout used for context",
    "  --json",
    "",
    "Options for remote-execution request create:",
    "  --component <id>          defaults to the primary component",
    "  --work-item <id>",
    "  --requesting-host <id>",
    "  --requesting-agent <id>",
    "  --target-host <id>",
    "  --capability <tag>         repeatable; required when --target-host is omitted",
    "  --runner-profile <id>",
    "  --repository <repository>",
    "  --ref <ref>",
    "  --command-profile <id>",
    "  --timeout-ms <ms>",
    "  --expected-artifact <ref>  repeatable",
    "  --mutation-class <none|verification|project_local|live_runtime|destructive>",
    "  --status <queued|accepted|running|completed|failed|blocked|timed_out|cancelled>",
    "  --attach-coordination-record <id>  repeatable",
    "  --json",
    "",
    "Options for remote-execution result record:",
    "  --status <queued|accepted|running|completed|failed|blocked|timed_out|cancelled>",
    "  --host <id>",
    "  --runner-profile <id>",
    "  --actual-ref <ref>",
    "  --actual-commit <commit>",
    "  --command <command>        repeatable",
    "  --exit-code <code>",
    "  --verification-outcome <passed|failed|not_run|blocked|timed_out|cancelled>",
    "  --output-tail <text>",
    "  --artifact <ref>           repeatable",
    "  --cleanup-status <not_required|completed|failed|blocked|unknown>",
    "  --blocker-safety-reason <text>",
    "  --json",
    "",
    "Options for remote-execution result get:",
    "  --json",
    "",
    "Options for remote-execution ssh-plan:",
    "  --home <path>            DevNexus home path with host-local overlays",
    "  --json",
    "",
    "Options for worktree prepare:",
    "  --component <id>          prepare a component-scoped worktree; defaults to the primary component",
    "  --workspace-meta          prepare a workspace/meta worktree rooted at the DevNexus workspace checkout",
    "  --work-item <id>          owning work item id used for branch naming and metadata",
    "  --work-item-title <text>",
    "  --topic <text>            human-readable topic used when --work-item is omitted",
    "  --branch <name>           branch to create; defaults to codex/<scope>/<work-item-or-topic>",
    "  --worktree-name <name>    directory name under the configured worktrees root",
    "  --base-ref <ref>          defaults to the component or workspace default branch",
    "  --no-base-ref             create the branch from the source checkout HEAD",
    "  --host <id>               lease host id; defaults to local hostname",
    "  --agent <id>              optional lease agent/chat id",
    "  --worker-agent <provider> assigned worker provider target, such as codex or claude",
    "  --write-scope <path>      intended lease write scope; repeatable",
    "  --lease-note <text>       lease note; repeatable",
    "  --json",
    "",
    "Options for publication branch-push:",
    "  --component <id>          defaults to the primary component",
    "  --project-repository      target the workspace metadata repository instead of a component",
    "  --branch <branch>         local branch/ref to push through the configured publication actor",
    "  --target-branch <branch>  optional destination branch; target-branch pushes still honor publication policy",
    "  --force-with-lease        update an existing review branch only if the remote ref was not changed unexpectedly",
    "  --force-with-lease-expected <sha>  expected remote branch commit for URL-backed push leases",
    "  --repository-path <path>  git checkout to push; defaults to current directory",
    "  --dry-run                 resolve the App credential and print the redacted push plan without running git",
    "  --json",
    "",
    "Options for publication pull-request upsert:",
    "  --component <id>          defaults to the primary component",
    "  --project-repository      target the workspace metadata repository instead of a component",
    "  --number <number>         update an existing pull request instead of creating one",
    "  --head <branch>           review branch to publish",
    "  --base <branch>           defaults to component or publication target branch",
    "  --title <text>",
    "  --body <text>",
    "  --body-file <path>",
    "  --json",
    "",
    "Options for publication pull-request merge:",
    "  --component <id>          defaults to the primary component",
    "  --project-repository      target the workspace metadata repository instead of a component",
    "  --number <number>",
    "  --method <merge|squash|rebase>  defaults to merge",
    "  --json",
    "",
    "Options for publication green-main plan:",
    "  --component <id>          defaults to the primary component",
    "  --pr <number>             pull request number to evaluate",
    "  --pr-url <url>",
    "  --head <branch>           candidate branch name for PR creation hints",
    "  --checks-file <json>      provider check report JSON, or {\"checks\": [...]}",
    "  --allow-rerun             allow one failed-run rerun when a reason is provided",
    "  --rerun-reason <text>",
    "  --rerun-attempted         mark the one allowed rerun as already used",
    "  --json",
    "",
    "Options for publication evidence normalize:",
    "  --required-check <name>   classify normalized evidence against a required check; repeatable",
    "  --json",
    "",
    "Options for publication merge-queue-readiness:",
    "  --component <id>          defaults to the primary component",
    "  --merge-queue-enabled",
    "  --merge-queue-disabled",
    "  --evidence-file <json>    provider evidence array, {\"evidence\": [...]}, or {\"providerEvidence\": [...]}",
    "  --workflow-triggers-file <json> workflow trigger array or {\"workflowTriggers\": [...]}",
    "  --json",
    "",
    "Options for publication train-readiness:",
    "  --version <id>            limit grouping to a configured version",
    "  --evidence-file <json>    provider check evidence array, {\"evidence\": [...]}, or {\"providerEvidence\": [...]}",
    "  --full-matrix-budget-available",
    "  --full-matrix-budget-exhausted",
    "  --json",
    "",
    "Options for publication candidate-plan:",
    "  --version <id>            select the version scope to batch; optional",
    "  --evidence-file <json>    provider check evidence array, {\"evidence\": [...]}, or {\"providerEvidence\": [...]}",
    "  --integration-branch <branch>",
    "  --candidate-branch <branch>",
    "  --full-matrix-budget-available",
    "  --full-matrix-budget-exhausted",
    "  --json",
    "",
    "Options for quick-fix plan/start/finish:",
    "  --component <id>          defaults to the primary component",
    "  --work-item <id>          GitHub issue id, for example github-50",
    "  --topic <text>",
    "  --branch <name>",
    "  --worktree-name <name>",
    "  --write-scope <path>      repeatable",
    "  --verification-command <command>  repeatable; defaults to component verification",
    "  --pr-url <url>            finish summary only",
    "  --merge-commit <sha>      finish summary only",
    "  --verification <text>     finish summary only",
    "  --cleanup-action <text>   finish summary only; repeatable",
    "  --json",
    "",
    "Options for work-item create:",
    "  --component <id>          defaults to the primary component",
    "  --tracker <id>            defaults to the component default tracker",
    "  --title <title>",
    "  --description <text>",
    "  --status <todo|ready|in_progress|blocked|done|wont_do>",
    "  --label <label>            repeatable",
    "  --assignee <assignee>      repeatable",
    "  --milestone <text>",
    "  --json",
    "",
    "Options for work-item discovery-status:",
    "  --json",
    "",
    "Options for work-item claim-next:",
    "  --component <id>          defaults to the primary component",
    "  --tracker <id>            defaults to the component default tracker",
    "  --mode <default|discovery>",
    "  --discovery               shortcut for --mode discovery",
    "  --host <id>               claiming host id",
    "  --agent <id>              optional claiming agent id",
    "  --owner <id>              optional logical owner id",
    "  --lease-ms <ms>           lease duration in milliseconds",
    "  --reclaim-stale           claim an expired in-progress optimistic claim",
    "  --stale-claim-policy <report|reclaim>",
    "  --json",
    "",
    "Options for work-item list:",
    "  --component <id>          defaults to the primary component",
    "  --tracker <id>            defaults to the component default tracker",
    "  --status <todo|ready|in_progress|blocked|done|wont_do|open|closed>  repeatable",
    "  --label <label>            repeatable",
    "  --assignee <assignee>      repeatable",
    "  --search <text>",
    "  --limit <count>",
    "  --json",
    "",
    "Options for work-item get:",
    "  --component <id>          defaults to the primary component",
    "  --tracker <id>            defaults to the component default tracker",
    "  --json",
    "",
    "Options for work-item update:",
    "  --component <id>          defaults to the primary component",
    "  --tracker <id>            defaults to the component default tracker",
    "  --title <title>",
    "  --description <text>",
    "  --clear-description",
    "  --status <todo|ready|in_progress|blocked|done|wont_do>",
    "  --label <label>            repeatable, replaces labels when provided",
    "  --clear-labels",
    "  --assignee <assignee>      repeatable, replaces assignees when provided",
    "  --clear-assignees",
    "  --milestone <text>",
    "  --clear-milestone",
    "  --json",
    "",
    "Options for work-item comment:",
    "  --component <id>          defaults to the primary component",
    "  --tracker <id>            defaults to the component default tracker",
    "  --body <text>",
    "  --json",
    "",
    "Options for work-item set-status:",
    "  --component <id>          defaults to the primary component",
    "  --tracker <id>            defaults to the component default tracker",
    "  --status <todo|ready|in_progress|blocked|done|wont_do>",
    "  --json",
    "",
    "Options for work-item link:",
    "  --component <id>          defaults to the primary component",
    "  --tracker <id>            configured tracker binding id",
    "  --provider <provider>",
    "  --host <host>",
    "  --repository-id <id>",
    "  --repository-owner <owner>",
    "  --repository-name <name>",
    "  --project-id <id>",
    "  --board-id <id>",
    "  --item-id <id>",
    "  --item-number <number>",
    "  --item-key <key>",
    "  --node-id <id>",
    "  --web-url <url>",
    "  --observed-at <iso-timestamp>",
    "  --json",
    "",
    "Options for work-item show-links:",
    "  --component <id>          defaults to the primary component",
    "  --json",
    "",
    "Options for work-item unlink:",
    "  --component <id>          defaults to the primary component",
    "  --tracker <id>            configured tracker binding id",
    "  --item-id <id>",
    "  --reason <text>",
    "  --json",
    "",
    "Options for work-item import-plan and import-execute:",
    "  --component <id>          defaults to the primary component",
    "  --source-tracker <id>     GitHub tracker binding id",
    "  --target-tracker <id>     local tracker binding id",
    "  --direction <external_to_local>",
    "  --status <todo|ready|in_progress|blocked|done|wont_do>  repeatable",
    "  --label <label>            repeatable",
    "  --assignee <assignee>      repeatable",
    "  --search <text>",
    "  --limit <count>",
    "  --field <title|description|status|labels|assignees|milestone>  repeatable",
    "  --status-map <source:target>  repeatable",
    "  --conflict-policy <block|source_wins|target_wins>",
    "  --write-create <plan|skip|block>",
    "  --write-update <plan|skip|block>",
    "  --write-link <plan|skip|block>",
    "  --fingerprint <external_ref|web_url|title>  repeatable",
    "  --credentials <not_required|available|missing>",
    "  --policy-reason <text>",
    "  --json",
    "",
    "Options for work-item sync-plan and sync-execute:",
    "  --component <id>          defaults to the primary component",
    "  --source-tracker <id>",
    "  --target-tracker <id>",
    "  --direction <source_to_target>",
    "  --open                    shortcut for todo, ready, in_progress, and blocked",
    "  --status <todo|ready|in_progress|blocked|done|wont_do>  repeatable",
    "  --label <label>            repeatable",
    "  --assignee <assignee>      repeatable",
    "  --search <text>",
    "  --limit <count>",
    "  --field <title|description|status|labels|assignees|milestone>  repeatable",
    "  --comment-policy <ignore|plan>",
    "  --status-map <source:target>  repeatable",
    "  --conflict-policy <block|source_wins|target_wins>",
    "  --write-create <plan|skip|block>",
    "  --write-update <plan|skip|block>",
    "  --credentials <not_required|available|missing>",
    "  --policy-reason <text>",
    "  --json",
    "",
    "Options for ci-failure-intake plan:",
    "  --input <json-file>         manual replay payload with policy, failure, and optional existingWorkItems",
    "  --json",
    "",
    "Options for automation status:",
    "  --home <path>             host-local home config for auth profiles",
    "  --json",
    "",
    "Options for automation eligible-work:",
    "  --mode <default|discovery>",
    "  --discovery               shortcut for --mode discovery",
    "  --json",
    "",
    "Options for automation agent-profiles:",
    "  --json",
    "",
    "Options for automation app-server-probe:",
    "  --profile <id>            app-server profile id; defaults to coordinator profile",
    "  --json",
    "",
    "Options for automation enqueue:",
    "  --title <title>",
    "  --description <text>",
    "  --status <todo|ready|in_progress|blocked|done|wont_do>",
    "  --label <label>            repeatable, added after selector labels",
    "  --assignee <assignee>      repeatable, added after selector assignees",
    "  --milestone <text>",
    "  --json",
    "",
    "Options for automation heartbeat prepare:",
    "  --name <name>",
    "  --interval-minutes <count>  defaults to 60",
    "  --paused                    prepare a paused heartbeat recipe",
    "  --json",
    "",
    "Options for automation target-cycle list:",
    "  --json",
    "",
    "Options for automation target-cycle record:",
    "  --cycle-id <id>             explicit id; must be unique in the target-cycle ledger",
    "  --run-id <id>",
    "  --status <started|dispatched|completed|blocked|failed|skipped>",
    "  --summary <text>",
    "  --eligible-work-items <count>",
    "  --work-item <component-id:id>  repeatable",
    "  --work-item-logical-id <id>",
    "  --work-item-tracker <id>",
    "  --work-item-status <selected|dispatched|in_progress|completed|blocked|failed|skipped>",
    "  --work-item-agent-profile <id>",
    "  --work-item-note <text>",
    "  --blocker <text>              repeatable",
    "  --note <text>                 repeatable",
    "  --json",
    "",
    "Options for automation target-report:",
    "  --json",
    "",
    "Options for automation run-once:",
    "  --command <command>        shell command to run; overrides automation.executor.command, automation.agent.command, or coordinator profile command",
    "  --run-id <id>",
    "  --owner <name>",
    "  --branch <name>",
    "  --worktree-name <name>",
    "  --base-ref <ref>",
    "  --full                     also run configured full verification commands",
    "  --timeout-ms <ms>          applies to each command",
    "  --json",
    "",
    "Options for automation schedule:",
    "  --command <command>        shell command to run; overrides automation.executor.command, automation.agent.command, or coordinator profile command",
    "  --owner <name>",
    "  --base-ref <ref>",
    "  --interval-ms <ms>         overrides project automation.schedule.intervalMs",
    "  --max-ticks <count>        stop after this many scheduler polls",
    "  --max-runs <count>         stop after this many run-once executions",
    "  --run-id-prefix <prefix>",
    "  --full                     also run configured full verification commands",
    "  --timeout-ms <ms>          applies to each command",
    "  --json",
    "",
    "Options for automation coordinator-loop:",
    "  --command <command>        coordinator command; overrides automation.agent.command or coordinator profile command",
    "  --adopt-current            return current-agent adoption context instead of launching a command",
    "  --run-id <id>              run id to use with --adopt-current",
    "  --owner <name>",
    "  --interval-ms <ms>         overrides project automation.schedule.intervalMs",
    "  --max-ticks <count>        stop after this many loop decisions",
    "  --max-runs <count>         stop after this many coordinator launches",
    "  --run-id-prefix <prefix>",
    "  --timeout-ms <ms>          applies to the coordinator command",
    "  --progress-jsonl           emit low-volume JSON Lines progress events to stderr",
    "  --json",
    "",
    "Options for automation current-agent adopt:",
    "  --run-id <id>",
    "  --owner <name>",
    "  --json",
    "",
    "Options for automation current-agent record:",
    "  --run-id <id>",
    "  --status <completed|blocked|failed|skipped>",
    "  --summary <text>",
    "  --commit <id>              repeatable",
    "  --verification-command <command>  repeatable",
    "  --verification-status <passed|failed|not_run>",
    "  --verification-summary <text>",
    "  --publication-type <not_decided|local_only|direct_integration|review_handoff|blocked>",
    "  --publication-remote <name>",
    "  --publication-target-branch <branch>",
    "  --publication-pr-url <url>",
    "  --publication-reason <text>",
    "  --error <text>",
    "  --json",
  ].join("\n");
}

export function projectSetupUsage(): string {
  return [
    "Usage:",
    "  dev-nexus workspace init [workspace-root] [options]",
    "",
    "Alias:",
    "  dev-nexus workspace setup [workspace-root] [options]",
    "",
    "User quickstart:",
    "  dev-nexus workspace init",
    "",
    "Run from the directory you want to use, or pass [workspace-root] for scripted setup.",
    "",
    "The DevNexus home defaults to DEV_NEXUS_HOME or ~/.dev-nexus.",
    "",
    "Options:",
    "  --home <path>",
    "  --answers <json-file>     setup answers for non-interactive automation",
    "  --dry-run                 preview only; omit to apply local setup writes",
    "  --json",
    "",
    "Provider mutations are not part of workspace setup.",
    "Use workspace hosting commands for repository creation, access repair, and other provider writes.",
  ].join("\n");
}

export function projectComponentAddUsage(): string {
  return [
    "Usage:",
    "  dev-nexus workspace component add <workspace-root> [options]",
    "",
    "Options:",
    "  --answers <json-file>     component answers with one or more components",
    "  --home <path>",
    "  --dry-run                 preview only; omit to update local workspace config/scaffold",
    "  --json",
    "",
    "Provider mutations are not part of component add.",
    "Use workspace hosting commands for repository creation, access repair, and other provider writes.",
  ].join("\n");
}
